name: Registrazione nuova azienda
description: Compila questo modulo per aggiungere una nuova azienda al portale IT Romagna
title: "Nuova azienda"
labels: ["registrazione-azienda"]

body:
  - type: input
    id: nome
    attributes:
      label: Nome azienda
      placeholder: "Es. Azienda Esempio SRL"
    validations:
      required: true

  - type: textarea
    id: descrizione
    attributes:
      label: Descrizione
      placeholder: "Breve descrizione dell'azienda"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email di contatto
      placeholder: "azienda@esempio.com"
    validations:
      required: true

  - type: input
    id: email-avvisi
    attributes:
      label: Email Avvisi
      description: Email per comunicazioni di servizio (lasciare vuoto nel caso sia la stessa dell'email di contatto)
      placeholder: "aziendaPrivate@esempio.com"

  - type: input
    id: telefono
    attributes:
      label: Telefono
      placeholder: "3331234567"

  - type: input
    id: sito
    attributes:
      label: Sito web
      placeholder: "https://www.esempio.it"

  - type: dropdown
    id: citta
    attributes:
      label: Città
      options:
        - Alfonsine
        - Bagnacavallo
        - Bertinoro
        - Brisighella
        - Castel Bolognese
        - Cervia
        - Cesenatico
        - Cesena
        - Coriano
        - Faenza
        - Forlì
        - Forlimpopoli
        - Fusignano
        - Gambettola
        - Imola
        - Longiano
        - Lugo
        - Meldola
        - Misano Adriatico
        - Ravenna
        - Riccione
        - Rimini
        - San Mauro Pascoli
        - Santarcangelo di Romagna
        - Savignano sul Rubicone
        - Verucchio
    validations:
      required: true
    
  - type: input
    id: via
    attributes:
      label: Via
      placeholder: "Es. Via Roma"

  - type: input
    id: numero-civico
    attributes:
      label: Numero Civico

  - type: dropdown
    id: ambiti
    attributes:
      label: Ambiti di lavoro
      description: Seleziona uno o più ambiti
      multiple: true
      options:
        - Software Development
        - Artificial Intelligence & Data
        - Cybersecurity
        - Cloud Computing & DevOps
        - IT Infrastructure & Networking
        - Managed Services & IT Support
        - Digital Platforms & Web Solutions
        - AR/VR, Multimedia & Creative Tech
        - UI/UX & Digital Experience
        - IoT & Embedded Systems
        - Business Software & Enterprise Solutions
        - IT Consulting & Digital Transformation
    validations:
      required: true

  - type: dropdown
    id: remoto
    attributes:
      label: Lavoro da remoto
      options:
        - "No"
        - Ibrido
        - Full Remote
        - Remote-first
        - Remote-friendly
        - Flessibile
        - Da concordare
      default: 0
    validations:
      required: true

  - type: dropdown
    id: dimensione
    attributes:
      label: Dimensione azienda
      options:
        - Startup
        - Scale-up
        - Micro impresa
        - Piccola impresa
        - Media impresa
        - Grande impresa
        - Enterprise
    validations:
      required: true

  - type: dropdown
    id: assume
    attributes:
      label: Assume personale
      options:
        - "No"
        - Sì
      default: 0
    validations:
      required: true

  - type: dropdown
    id: tirocini
    attributes:
      label: Offre tirocini
      options:
        - "No"
        - Sì
    validations:
      required: true

  - type: textarea
    id: logo
    attributes:
      label: URL del logo (opzionale)
      placeholder: "logo.png"

  - type: checkboxes
    id: privacy
    attributes:
      label: Accettazione Privacy e Termini
      description: Devi accettare per poter inviare la richiesta
      options:
        - label: Dichiaro di aver letto e accettato la [Privacy Policy](https://portaleDIR/privacy) e i [Termini del servizio](https://portaleDIR/termini)
          required: true