name: Aggiungi azienda da Issue

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  convert:
    if: contains(github.event.issue.labels.*.name, 'registrazione-azienda')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Aggiungi azienda al JSON
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          node .github/scripts/aggiungiAzienda.js

      - name: Crea Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            title: "Nuova azienda da Issue #${{ github.event.issue.number }}"
            body: "Aggiunta automatica da Issue #${{ github.event.issue.number }}"
            commit-message: "Agiunta nuova azienda da issue #${{ github.event.issue.number }} "
            branch: "azienda-${{ github.event.issue.number }}"
            add-paths: |
              src/data/aziende.json
              public/loghi/**
